### ISSUE TITLE
Autoscaler Docs: Completar com algumas informações

### ISSUE THREAD

**Issue by Dentxinho** [b2wdigital/asgard-api#194]
Ao ler a [documentação do Autoscaler](https://docs.asgard.b2w.io/userguide/autoscaler/index.html), achei alguns pontos que podem ficar mais claros:

- [x] qual é o uso de recursos sugerido na app do autoscaler que rodará no próprio Asgard.
- [x] de quanto em quanto tempo o Autocaler roda para executar o trabalho.
- [x] qual a URL da imagem docker do Asgard. Hoje ainda não existe uma imagem da API do Asgard publicada no Docker Hub. Vai ser necessário criar uma antes de atualizar a doc.

@rockerbacon

**Comment by rockerbacon** [comment]
@daltonmatos percebi que não há URL para imagem do Asgard na documentação. A imagem só está disponível em repositório privado?

**Comment by daltonmatos** [comment]
Atualmente sim. Mas podemos amanhã fazer um build e publicar no docker hub. Essa imagem, a princípio, não tem nenhuma informação sensível e pode ser pública sem problemas.

**Comment by daltonmatos** [comment]
@rockerbacon, marquei aqui os itens que já estão feitos.

**Comment by rockerbacon** [comment]
@daltonmatos adicionei as referências à imagem no DockerHub

**Comment by rockerbacon** [comment]
@daltonmatos, coloquei algumas recomendações de utilização de recursos baseado no que estava configurado em HMG.
