### ISSUE TITLE
Autoscaler :: Gera informação de logs mesmo quando não executa a ação

### ISSUE THREAD

**Issue by Dentxinho** [b2wdigital/asgard-api#195]
Quando o `previous_value` é igual ao `new_value`, o autoscaler gera log, mesmo sem executar nenhuma ação.
```
{"logged_at": "2020-01-15T17:30:42.092637", "line_number": 55, "function": "decide_scaling_actions", "level": "INFO", "file_path": "/opt/app/asgard/workers/autoscaler/simple_decision_component.py", "appname": "my/app", "event": "CPU_SCALE_UP", "previous_value": 0.1, "new_value": 0.1}
{"logged_at": "2020-01-15T17:30:42.092857", "line_number": 100, "function": "decide_scaling_actions", "level": "INFO", "file_path": "/opt/app/asgard/workers/autoscaler/simple_decision_component.py", "appname": "my/app", "event": "MEM_SCALE_UP", "previous_value": 64.0, "new_value": 64.0}
```

Acho que esses logs não deveriam ser gerados, ou deveria existir um outro tipo de log informando que a aplicação foi impactada pela decisão de escalar.

**Comment by rockerbacon** [comment]
Isso está ocorrendo pois o componente de decisão está de fato decidindo escalar a APP, mas os valores decididos estão sendo normalizados de acordo com os valores mínimos/máximos configurados. Um ajuste será feito para cobrir esse caso

**Comment by rockerbacon** [comment]
@daltonmatos Essa issue já pode ser fechada
